<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Premium Plan</name>
   <tag></tag>
   <elementGuidId>2041fcd2-c580-4861-8d49-bbc4c54a67a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c0f19d57-fede-4cc2-baf4-23f67cbe681b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>56113697-44a8-4f13-a26e-ebd70a707864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gswNZR bbLVwL account-setting-tab</value>
      <webElementGuid>cdfa2ee4-4de7-4a80-87d0-6fd5ba22e41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Premium Plan</value>
      <webElementGuid>d4220aa9-dc56-445a-bfde-8e33af6278ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)</value>
      <webElementGuid>6a21f9b4-fa9c-41dd-82dc-5e90263adf5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='2']</value>
      <webElementGuid>684babbe-3056-41e3-82d8-6a86fb935565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/ul/li[3]</value>
      <webElementGuid>9368fbac-e30e-4f0f-a9e7-50c1e947314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/following::li[3]</value>
      <webElementGuid>e1fcf13d-6646-4bf8-ad4d-e74f037d9bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::li[3]</value>
      <webElementGuid>0dc647f1-9232-4588-ac69-f88e6b722ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::li[2]</value>
      <webElementGuid>59091d2c-b705-482b-a943-fb0605ebd95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]</value>
      <webElementGuid>e7c4bccd-398f-482b-b488-b7b0c03d4b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '2' and (text() = 'Premium Plan' or . = 'Premium Plan')]</value>
      <webElementGuid>3d1b4499-2804-4e87-9974-efbca6e81697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
