<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Game Setting</name>
   <tag></tag>
   <elementGuidId>8a50b9c9-957f-4c26-b383-72f449d87ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3eeb146f-6a8a-4308-bc40-0307a9e6de56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>229c74e9-ab42-439d-8c43-5a9f2db7126a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gswNZR bbLVwL account-setting-tab</value>
      <webElementGuid>a11f2b33-e1ac-46d8-b09e-6d72c8e8f153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Game Setting</value>
      <webElementGuid>bbb98a98-9944-4f00-829a-d9c908a51202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)</value>
      <webElementGuid>4c7b0063-65ef-4efc-a7f9-f89b3b7b89d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='4']</value>
      <webElementGuid>1f5b4ee3-b87d-4565-af42-290a945c3bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/ul/li[4]</value>
      <webElementGuid>63a73b57-6193-426e-9af8-82a140b6be4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/following::li[4]</value>
      <webElementGuid>2af86cda-05e3-47a3-ad35-5c533f443b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::li[4]</value>
      <webElementGuid>ba02ad02-6f6d-4ef0-95c1-86bd5d41e42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::li[1]</value>
      <webElementGuid>f3a8a908-9045-4891-becb-e9350ea0ffda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[4]</value>
      <webElementGuid>d3d134bc-6f29-4c91-a17a-fbae2a57d138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '4' and (text() = 'Game Setting' or . = 'Game Setting')]</value>
      <webElementGuid>28fa381b-a06f-4d5a-b118-b1f9d2abc018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
