<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Personal Details</name>
   <tag></tag>
   <elementGuidId>11a0f32e-3a02-4678-b23e-b7971aa5a371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca0c44d3-0836-4254-a880-5d8278b680c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>14bc3800-ef85-442d-8e8e-1a0f8fc3de00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gswNZR bbLVwL account-setting-tab tab-active</value>
      <webElementGuid>1e49d5b9-be9e-4809-9b0c-2549e2bae701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal Details</value>
      <webElementGuid>5ce7814a-1d0b-4068-8873-2a2a90a8f89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-account-setting&quot;]/ul[@class=&quot;sc-bcXHqe sZiLj account-setting-header&quot;]/li[@id=&quot;0&quot;]</value>
      <webElementGuid>7cfd6ce4-7d59-4d5b-9130-521da9c348b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='0']</value>
      <webElementGuid>368670a2-d19a-456d-9ffc-e8ee39606aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/ul/li</value>
      <webElementGuid>657bf17a-b617-44a4-8192-927cdefe99ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/following::li[1]</value>
      <webElementGuid>5a719754-82ae-4ee7-a7f8-d1ef255b7b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::li[1]</value>
      <webElementGuid>2e5e260a-685d-4f34-8bc3-b6b724cc2f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::li[4]</value>
      <webElementGuid>b7d9b2b8-3e2d-4250-af3f-1f17b970ffae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li</value>
      <webElementGuid>ad1344ba-f993-483f-911a-31e25b4e65ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '0' and (text() = 'Personal Details' or . = 'Personal Details')]</value>
      <webElementGuid>1f264511-e5f5-4a0b-8038-1f0c0568f854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
