<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Explore on my own</name>
   <tag></tag>
   <elementGuidId>7589e5cc-f4c8-4251-b299-4f7b2611ce71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.justify-content-between.mt-3 > button[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[31]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fed7cd9-384b-4ef8-ae83-2996834267f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>534b0543-aeb7-49ba-b772-e4c3c540d9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Explore on my own</value>
      <webElementGuid>8098a007-c942-4506-90c4-652595c7435d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;mx-md-auto p-0&quot;]/div[@class=&quot;d-flex gap-3 justify-content-center&quot;]/div[@class=&quot;d-flex flex-column justify-content-between&quot;]/div[@class=&quot;d-flex justify-content-between mt-3&quot;]/button[1]</value>
      <webElementGuid>941e0274-4dd0-44c8-b384-cdb0ee73c03a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[31]</value>
      <webElementGuid>55a76bc4-ba6c-4370-99bd-43ccb122308d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>efa078b2-1822-4f77-8914-63704d742db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Me Plan/Post My Clips'])[1]/following::button[1]</value>
      <webElementGuid>2ffa2aa2-1985-4dba-8e9d-d468519f9d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert Clips to TikTok format'])[1]/following::button[1]</value>
      <webElementGuid>36985d73-2c59-469b-8ceb-2afbe2567e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[1]</value>
      <webElementGuid>0b3f7e48-a0a9-43d2-8bbf-f633660904e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms'])[1]/preceding::button[2]</value>
      <webElementGuid>52233afc-5354-4599-a68f-476c5ec2e364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Explore on my own']/parent::*</value>
      <webElementGuid>f5e4b5ab-bf60-4a37-b8d1-472e262d1669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>cdddbc50-172c-4d6c-836c-fde7a22203fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Explore on my own' or . = 'Explore on my own')]</value>
      <webElementGuid>85caf7fb-ed4c-437f-8c5c-406f44e356df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
