<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>6c0efbf7-5486-44c1-9d15-772d570e7d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tutorial-video_html5_api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='tutorial-video_html5_api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>3f71c627-ce21-4c55-b813-7285ca2dfe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tutorial-video_html5_api</value>
      <webElementGuid>52d298d3-5d88-4096-9123-36505c3f1c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a6b5adcd-1b78-486d-8a82-4ed49af072df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>bcffc306-4f1a-421a-8cf7-e5b30c8f1337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8bdd4f13-c1ec-4ba8-a3c2-609b54fa96a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>6f8fe4b9-d2c5-4bba-b61d-160cb411d105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>muted</name>
      <type>Main</type>
      <value>muted</value>
      <webElementGuid>997d3869-9d55-4299-af19-43de0122e715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>playsinline</name>
      <type>Main</type>
      <value>playsinline</value>
      <webElementGuid>159c3458-ed72-4402-8e8f-25cd532c4fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dhf62eo10occ1.cloudfront.net/assets/stream-demo/warfare2/high_viewer_v1882728593_2_08-03-2023.mp4</value>
      <webElementGuid>67d8a1bf-2783-4529-a9af-83b9a20b99a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tutorial-video_html5_api&quot;)</value>
      <webElementGuid>b39ceda3-2c39-4cdc-8b23-c2f49f258c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='tutorial-video_html5_api']</value>
      <webElementGuid>763e7fb9-a5ec-4fb3-86db-0104fa1b6b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tutorial-video']/video</value>
      <webElementGuid>cdadc9aa-6d62-4a24-9ffd-c2708e62273e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>b33a3a1a-8659-4490-93e5-801fbd7009b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'tutorial-video_html5_api' and @src = 'https://dhf62eo10occ1.cloudfront.net/assets/stream-demo/warfare2/high_viewer_v1882728593_2_08-03-2023.mp4']</value>
      <webElementGuid>bde658a1-64f0-43ff-a9ff-ed12ab01b3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
