<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_StreamVideo</name>
   <tag></tag>
   <elementGuidId>46e046e5-feff-4c34-9c96-b618af0870ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sidebar-submenu-link > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submenu-1']/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3658a14f-ca50-44f6-b566-d3937793b718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stream/Video</value>
      <webElementGuid>5091c8e0-a71b-494e-b7f1-578d74af4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-1&quot;)/ul[1]/li[1]/a[@class=&quot;sidebar-submenu-link&quot;]/span[1]</value>
      <webElementGuid>50bad37e-b92b-4bd6-b478-54e4dc79f369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submenu-1']/ul/li/a/span</value>
      <webElementGuid>88939a0e-5305-4359-a428-991af4a09a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clip Library'])[1]/following::span[1]</value>
      <webElementGuid>bb736a91-49ff-4e01-b6c8-7d029b4202fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[2]</value>
      <webElementGuid>a6a6c203-b2c2-4c3e-9ea7-6b37997aef64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitch/Kick Clips'])[1]/preceding::span[1]</value>
      <webElementGuid>4538dd66-d306-4a4b-9a8c-430e10a41e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playlist'])[1]/preceding::span[2]</value>
      <webElementGuid>6694ac5d-326b-47d1-aa4e-6d9c84cb2490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stream/Video']/parent::*</value>
      <webElementGuid>cc50b969-3c92-45c4-b3e5-f9164b402888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/span</value>
      <webElementGuid>eb4db637-8abb-4560-b122-35c27daa5384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Stream/Video' or . = 'Stream/Video')]</value>
      <webElementGuid>98f3193d-42d1-4e0f-bbec-fbc3326f39ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
